### ISSUE TITLE
[STYLE]  style/signup

### ISSUE THREAD

**Issue by ilovezerocokeya** [gather-here/gather_here#113]
## Description

signupForm 위아래 여백 맞추기
웰컴 이미지 변경

## To-Do

- [x] Signup01 02 03 위 아래 여백 맞추기
- [x] 웰컴 이미지 변경

## up-to-date
 240805
### 작업이 완료 예정인 시점을 적어주세요
240805

**Comment by leeboa2005** [comment]
머지 완료
