### ISSUE TITLE
[UPDATE] feature/headerloginlogout

### ISSUE THREAD

**Issue by ilovezerocokeya** [gather-here/gather_here#27]
## Description
 헤더에 로그인인시 로그아웃으로 바뀌게 만들기
 로그아웃 기능 만들기
## To-Do

-   [x] 헤더에 로그인인시 로그아웃으로 바뀌게 만들기
-   [x] 로그아웃 기능 만들기

### 기타 알려야 하는 상황을 적어주세요
www.localhost:3000/api/auth/callback으로 주소 바꿨습니다.

## up-to-date
240725

### 작업이 완료 예정인 시점을 적어주세요
240725

**Comment by ilovezerocokeya** [comment]
헤더부분에 로그인/로그아웃 작업했습니다. 그리고 아까 잘못 작성했던 url도 localhost:3000으로 변경했습니다.

**Comment by leeboa2005** [comment]
완료되어서 닫아요~!
