### ISSUE TITLE
[UPDATE] feature/loginModal

### ISSUE THREAD

**Issue by ilovezerocokeya** [gather-here/gather_here#33]
## Description
로그인페이지에 모달을 적용해보려고 합니다.
## To-Do

-   [x] 모달에 로그인화면 적용

### 기타 알려야 하는 상황을 적어주세요
1. contextProvider를 header까지 감싸는걸로 수정했습니다,.
2.  Common > Modal> CommonModal.tsx에서 z-index를 추가하여 z-10으로 수정했습니다.
3.  패러렐 라우트와 인터셉팅 라우트를 사용해서 모달을 구현하려고했는데 지금 저희조의 컨셉과는 조금 맞지 않은것 같아서 일반 모달로 방향을 바꿨습니다.

## up-to-date
240726

### 작업이 완료 예정인 시점을 적어주세요
240727

**Comment by leeboa2005** [comment]
완료되어서 닫아요~!
